version: '2'
services:
  fixedassets-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/fixedAssets/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fixedAssets
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
